name: Unit Tests

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        host-os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9"]
      fail-fast: false

    runs-on: ${{ matrix.host-os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: testenv
          allow-softlinks: true
          auto-activate-base: false
          auto-update-conda: true
          channel-priority: flexible
          channels: conda-forge
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          show-channel-urls: true
          use-only-tar-bz2: false

      - name: Set up Visual Studio shell
        if: runner.os == 'Windows'
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install build requirements
        run: |
          set -vxeuo pipefail
          conda install -y cmake

      - name: Build sdist and wheel and install *.whl
        run: |
          set -vxeuo pipefail
          cd python
          python -VV
          python setup.py sdist bdist_wheel
          ls -la dist/*
          pip install -v dist/*.whl

      - name: Install test requirements
        run: |
          set -vxeuo pipefail
          cd python
          python -m pip install -r requirements-dev.txt
          python -m pip list

      - name: Test with pytest
        run: |
          set -vxeuo pipefail
          # cp -rv python/srwpy/tests tests
          # pytest -s -vv --import-mode=importlib python/srwpy/tests/
          pytest -s -vv --pyargs srwpy
